### ISSUE TITLE
Cleanup the repos

### ISSUE THREAD

**Issue by gusbemacbe** [chriscpritchard/gentoo-wsl2#1]
Hello,

After following the whole [instruction](https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Base#Configuring_Portage) and the complete installation, can I clean the `/var/db/repos/gentoo` or the snapshots or the `tar.xz`s? It took more than 3 GB.

**Comment by chriscpritchard** [comment]
Hi, sorry! Totally missed this, you can delete the snapshots and tar.xz but not /var/db/repos/gentoo
